### ISSUE TITLE
报错了，啥情况

### ISSUE THREAD

**Issue by ZuyongWu** [bubbliiiing/yolox-tf2#1]
train里面使用的s版本不报错，换成l版本的就跑到一半报错了
![image](https://user-images.githubusercontent.com/43801775/142164735-94fae369-59c5-4474-9f47-7efaa8836473.png)

**Comment by bubbliiiing** [comment]
不知道……可能爆显存了？改小batch试试？

**Comment by ZuyongWu** [comment]
> 不知道……可能爆显存了？改小batch试试？

并不是啊，他是训练到一半的时候报的，GPU监控显示显存没有爆。另外，每次运行都会有这个提示，我怀疑跟它有关，但又不知道怎么改
UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "

**Comment by bubbliiiing** [comment]
Warning都可以忽略的，……主要是上面这个，我都没法知道是哪一行错了，就很烦，而且s没错……

**Comment by bubbliiiing** [comment]
是不是内存不足了？

**Comment by ZuyongWu** [comment]
改了batch，没报错了，不知道什么原因
