### ISSUE TITLE
自定义SiLU不支持保存模型重新加载

### ISSUE THREAD

**Issue by xxr11** [bubbliiiing/yolox-tf2#15]
up你好，如果保存模型参数和结构然后重新load的话，其中SiLU和Focus层是不支持的，因为它们不是tf2预定义的层类，先请问下SiLU函数可不可以通过在模型静态图定义的过程中，更改为tf.nn.silu()，因为不太熟悉tf2，所以希望up能提供关于一些修改silu的思路，Focus层已经解决了，不胜感激

**Comment by bubbliiiing** [comment]
emm，这样好像貌似还是要自定义层，tf.nn可以呀。

**Comment by xxr11** [comment]
嗯嗯 是我不太了解tf2的原因 去学习了一下 问题已解决

**Comment by bubbliiiing** [comment]
好的
